---

- name: Add user to Keycloak
  hosts: keycloak
  gather_facts: no
  vars:
#  - keycloak_base_url: "https://<keycloak-host>:<port>" # from inventory file 
  - keycloak_admin_user: "{{ vault_keycloak_admin_user }}"
  - keycloak_admin_password: "{{ vault_keycloak_admin_password }}"
  - keycloak_admin_realm: master
#  - keycloak_target_realm: "realm" # from inventory file
  - keycloak_users: "{{ users }}"

  tasks:
  - name: Login to Keycloak
    ansible.builtin.include_role:
      name: login
    vars:
      base_url: "{{ keycloak_base_url }}"
      realm: "{{ keycloak_admin_realm }}"
      admin_user: "{{ keycloak_admin_user }}"
      admin_password: "{{ keycloak_admin_password }}"

  - name: Update user
    ansible.builtin.include_role:
      name: manage-user
    vars:
      base_url: "{{ keycloak_base_url }}"
      realm: "{{ keycloak_target_realm }}"
      access_token: "{{ keycloak_access_token }}"
      username: "{{ item.username }}"
      first_name: "{{ item.firstname }}"
      last_name: "{{ item.lastname }}"
      email: "{{ item.email }}"
      enabled: "{{ item.enabled }}"
      client_roles: "{{ item.clientroles | flatten(levels=1) }}"
      user_groups: "{{ item.groups | list }}"
      state: "{{ item.state }}"
    loop: "{{ keycloak_users | flatten(levels=1) }}"
