# roles/add-client-role-to-user/tasks/main.yml

- name: Echo client id and role name
  ansible.builtin.debug:
    msg: "Adding client role '{{ client_id }}' - '{{ client_role_name }}'"

- name: Debug client role name
  ansible.builtin.debug:
    var: client_role_name
    verbosity: 1

- name: Get client id
  ansible.builtin.uri:
    url: "{{ base_url }}/auth/admin/realms/{{ realm }}/clients?clientId={{ client_id }}"
    method: GET
    headers:
      Accept: "*/*"
      Authorization: "Bearer {{ access_token }}"
    body_format: form-urlencoded
    validate_certs: no
  register: client
  ignore_errors: yes

- name: Debug client
  ansible.builtin.debug:
    var: client.json
    verbosity: 1

- name: Get client role
  ansible.builtin.uri:
    url: "{{ base_url }}/auth/admin/realms/{{ realm }}/clients/{{ client.json[0].id }}/roles/{{ client_role_name }}"
    method: GET
    headers:
      Accept: "*/*"
      Authorization: "Bearer {{ access_token }}"
    body_format: form-urlencoded
    validate_certs: no
  register: client_role
  ignore_errors: yes

- name: Debug client role
  ansible.builtin.debug:
    var: client_role.json
    verbosity: 1

- name: Get user role mappings
  ansible.builtin.uri:
    url: "{{ base_url }}/auth/admin/realms/{{ realm }}/users/{{ user_uuid }}/role-mappings/clients/{{ client.json[0].id }}"
    method: GET
    headers:
      Accept: "*/*"
      Authorization: "Bearer {{ access_token }}"
    body_format: form-urlencoded
    validate_certs: no
  register: user_role_mappings
  ignore_errors: yes

- name: Debug user role mapping
  ansible.builtin.debug:
    var: user_role_mappings.json
    verbosity: 1

- name: Set existing client role id as fact
  ansible.builtin.set_fact:
    existing_client_role_id: "null"

- name: Set existing client role id as fact
  ansible.builtin.set_fact:
    existing_client_role_id: "{{ user_role_mappings.json | json_query( client_role_query ) }}"
  vars:
    client_role_query: "[? id=='{{ client_role.json.id }}'].{ id: id }"
  when: user_role_mappings.json | length > 0

- name: Debug existing client role id
  debug:
    var: existing_client_role_id
    verbosity: 1

- name: Add user to client role
  ansible.builtin.uri:
    url: "{{ base_url }}/auth/admin/realms/{{ realm }}/users/{{ user_uuid }}/role-mappings/clients/{{ client.json[0].id }}"
    method: POST
    headers:
      Accept: "*/*"
      Authorization: "Bearer {{ access_token }}"
    body_format: json
    validate_certs: no
    status_code: 204
    body: "[{ 
            \"attributes\": {},
            \"clientRole\": true,
            \"composite\": false,
            \"description\": \"${role_{{ client_role_name }}}\",
            \"id\": \"{{ client_role.json.id }}\",
            \"name\": \"{{ client_role_name }}\"
          }]"
