all:
  hosts:
  keycloak:
    localhost:
      ansile_connection: local
  vars:
    keycloak_target_realm: realm
    keycloak_base_url: https://<keycloak-host>:<port>
    users:
      - state: present
        username: user
        firstname: user
        lastname: name
        email: example@example.org
        enabled: true
        clientroles:
          - client: client-name
            role: role-name
        groups:
          - group
    keycloak_groups:
      - name: example-group
        state: present
    keycloak_clients:
    - state: present # default: present
      client_id: odoo.example.com
      name: Odoo OAuth Client
      description: Default client for Odoo instances
      enabled: False # default: True
      protocol: openid-connect # default: openid-connect
      client_authenticator_type: client-secret # default: client-secret
      standard_flow_enabled: True # default: True
      implicit_flow_enabled: False # default: False
      direct_access_grants_enabled: False # default: False
      root_url: "${authBaseUrl}"
      redirect_uris:
      - https://erp.example.com/*
      base_url: /realms/my-realm.com/account/
      full_scope_allowed: True # default: False
